author: Anders Holmgren <andersmholmgren@gmail.com>
description: A library for maintaining sets of related Dart projects versioned in git, in particular managing dependencies between them.
homepage: https://github.com/Andersmholmgren/jefe
name: jefe
version: 0.2.7
dependencies: 
  analyzer: '>=0.25.0+1'
  frappe: '^0.4.0+4'
  git: '^0.4.4+1'
  http: '^0.11.2'
  logging: '^0.10.0'
  option: '^1.1.0'
  pub_semver: '^1.1.0'
  quiver: '^0.21.3'
  stack_trace: '^1.3.1'
  unscripted: '^0.6.0'
  yaml: '^2.0.1+1'
  dockerfile: 
    git: 
      ref: cb21b1b6528a4335e0f04adf65e1de770e807e9a
      url: git@github.com:Andersmholmgren/dockerfile.git
  pubspec: 
    git: 
      ref: ebc33f71a483a8b88914a119ba46f87c96b5e083
      url: git@github.com:Andersmholmgren/pubspec.git
  yamlicious: 
    git: 
      ref: 5f5d618b5d7a9936cc813f262aefd5d8007b97ff
      url: git@github.com:Andersmholmgren/yamlicious.git
dependency_overrides: 
dev_dependencies: 
  mockito: '^0.8.2'
  test: '^0.12.7'
environment: 
  sdk: '>=1.9.0 <2.0.0'
executables: 
  jefe: null
