author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for maintaining sets of related Dart projects versioned in git, in particular managing dependencies between them."
homepage: "https://github.com/Andersmholmgren/jefe"
name: "jefe"
version: "0.2.10"
dependencies: 
  analyzer: ">=0.25.0+1"
  collection: "^1.4.0"
  frappe: "^0.4.0+4"
  git: "^0.4.4+1"
  http: "^0.11.2"
  logging: "^0.10.0"
  option: "^1.1.0"
  pub_semver: "^1.1.0"
  quiver: "^0.21.3"
  stack_trace: "^1.6.1"
  unscripted: "^0.6.0"
  yaml: "^2.0.1+1"
  dockerfile: 
    git: 
      ref: "13512aa512f5e27e74c6617b7cce4fe099bc7515"
      url: "git@github.com:Andersmholmgren/dockerfile.git"
  pubspec: 
    git: 
      ref: "7e1edc7391f1eb8692ae13e726bf53f49c24d089"
      url: "git@github.com:Andersmholmgren/pubspec.git"
  yamlicious: 
    git: 
      ref: "bad84cd0d8b8d16a244987b42cc7fb5c130ea3fe"
      url: "git@github.com:Andersmholmgren/yamlicious.git"
dev_dependencies: 
  mockito: "^0.8.2"
  test: "^0.12.10"
environment: 
  sdk: ">=1.9.0 <2.0.0"
executables: 
  jefe: null
