author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for maintaining sets of related Dart projects versioned in git, in particular managing dependencies between them."
homepage: "https://github.com/Andersmholmgren/jefe"
name: "jefe"
version: "1.0.0"
dependencies: 
  analyzer: "^0.32.5"
  args: "^1.5.0"
  collection: "^1.14.11"
  dockerfile: "^0.1.0"
  git: "^0.5.1+1"
  http: "^0.12.0"
  logging: "^0.11.3+2"
  path: "^1.6.2"
  pub_semver: "^1.4.2"
  pubspec: "^0.1.0"
  quiver: "^2.0.0+1"
  stack_trace: "^1.9.3"
  stuff: "^0.1.0"
  xml: "^3.2.3"
  yaml: "^2.1.15"
  yamlicious: "^0.1.0"
dev_dependencies: 
  mockito: "^3.0.0"
  test: "^1.3.3"
environment: 
  sdk: ">=1.9.0 <3.0.0"
executables: 
  jefe: null
