author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for maintaining sets of related Dart projects versioned in git, in particular managing dependencies between them."
homepage: "https://github.com/Andersmholmgren/jefe"
name: "jefe"
version: "0.4.0"
dependencies: 
  analyzer: ">=0.25.0+1"
  args: any
  collection: ">=1.4.0"
  dockerfile:
    path: ../dockerfile
#  frappe: ">=0.4.0+4"
  git: ">=0.4.4+1"
  http: ">=0.11.2"
  logging: ">=0.10.0"
#  option: ">=1.1.0"
  pub_semver: ">=1.1.0"
  pubspec:
    path: ../pubspec
  quiver: ">=0.21.3"
  stack_trace: ">=1.6.1"
#  unscripted:
#    git: https://github.com/Dart2WebRTC/unscripted.git
  xml: ">=2.4.2"
  yaml: ">=2.0.1+1"
  yamlicious:
    path: ../yamlicious
dev_dependencies: 
  mockito: ">=0.8.2"
  test: ">=0.12.10"
environment: 
  sdk: ">=1.9.0 <3.0.0"
executables: 
  jefe: null
