name: jefe
version: 0.0.1
description: A library for maintaining sets of related Dart projects versioned in git
author: Anders Holmgren <andersmholmgren@gmail.com>
homepage: https://github.com/Andersmholmgren/dockerfile
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  git: '^0.4.1+1'
#  grinder: '^0.6.2'
  pub_semver: '^1.1.0'
  option: any
  yaml: "^2.0.1+1"
  quiver: any
  logging: any
  frappe: any
  unscripted: any
  stack_trace: any
  pubspec: '^0.0.1+2'
  yamlicious: '^0.0.1'
  dockerfile: '^0.0.1'
#  den_api: any
dev_dependencies:
  unittest: any
  scheduled_test: any
  mockito: any
executables:
  jefe: