author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for maintaining sets of related Dart projects versioned in git, in particular managing dependencies between them."
homepage: "https://github.com/Andersmholmgren/jefe"
name: "jefe"
version: "0.2.7"
dependencies: 
  analyzer: ">=0.25.0+1"
  dockerfile: "^0.0.2"
  frappe: "^0.4.0+4"
  git: "^0.4.4+1"
  http: "^0.11.2"
  logging: "^0.10.0"
  option: "^1.1.0"
  pub_semver: "^1.1.0"
  pubspec: "^0.0.6"
  quiver: "^0.21.3"
  stack_trace: "^1.3.1"
  unscripted: "^0.6.0"
  yaml: "^2.0.1+1"
  yamlicious: "^0.0.4"
dev_dependencies: 
  mockito: "^0.8.2"
  test: "^0.12.7"
environment: 
  sdk: ">=1.9.0 <2.0.0"
executables: 
  jefe: null
