name: devops
version: 0.0.1
description: A minimal command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  git: '^0.4.1+1'
#  grinder: '^0.6.2'
  pub_semver: '^1.1.0'
  option: any
  yaml: "^2.0.1+1"
  quiver: any
  logging: any
#  den_api: any
dev_dependencies:
  unittest: any
  scheduled_test: any