name: jefe
version: 0.0.5+1
description: A library for maintaining sets of related Dart projects versioned in git, in particular managing dependencies between them.
author: Anders Holmgren <andersmholmgren@gmail.com>
homepage: https://github.com/Andersmholmgren/jefe
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  git: '^0.4.1+1'
  pub_semver: '^1.1.0'
  option: '^1.1.0'
  yaml: "^2.0.1+1"
  quiver: '^0.21.3'
  logging: '^0.10.0'
  frappe: '^0.4.0+4'
  unscripted: '^0.6.0'
  stack_trace: '^1.3.1'
  pubspec: '^0.0.1+2'
  yamlicious: '^0.0.1'
  dockerfile: '^0.0.1'
#  den_api: any
dev_dependencies:
  unittest: '^0.11.5+4'
  scheduled_test: '0.11.8'
  mockito: '^0.8.2'
executables:
  jefe: